### ISSUE TITLE
Add "5-minute intro" to show basic usage

### ISSUE THREAD

**Issue by aaaaalbert** [deepjaisia/SandboxHttpsExtensions#1]
I think the current README should be split into multiple parts, and one part should be a very quick intro into using the code. Something similar to Seattle Testbed's take-home assignment will make sense, so that the reader gets an idea about what your sandbox extensions do. Also, this should contain example output to compare what the reader sees on their screen.

The contents could be something among the lines:

---

In this 5-minute walkthrough, we will check out the HTTPS-enabled RepyV2 sandbox and run a simple example script.

We assume you have Git, Python 2, and OpenSSL installed. Clone the appropriate repo and build it (see the Seattle Testbed BuildInstructions [ link ] for details):

``` bash
~$ git clone https://github.com/deepjaisia/repy_v2.git -b add_test_call_to_sandbox ./deep_repy_v2
Cloning into './deep_repy_v2'...
cd remote: Counting objects: 1796, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 1796 (delta 2), reused 0 (delta 0), pack-reused 1789
Receiving objects: 100% (1796/1796), 1.37 MiB | 0 bytes/s, done.
Resolving deltas: 100% (930/930), done.
Checking connectivity... done.
~$ cd ./deep_repy_v2
~/deep_repy_v2$ cd scripts/
~/deep_repy_v2/scripts$ python initialize.py 
Checking out repo from https://github.com/SeattleTestbed/seattlelib_v2 ...
pyDone!
Checking out repo from https://github.com/SeattleTestbed/portability ...
thon Done!
Checking out repo from https://github.com/SeattleTestbed/seash ...
bzuuDone!
Checking out repo from https://github.com/SeattleTestbed/affix ...
  Done! 
Checking out repo from https://github.com/SeattleTestbed/common ...
Done!
Checking out repo from https://github.com/SeattleTestbed/utf ...
Done!
~/deep_repy_v2/scripts$ python build.py 
Building into /home/albert/deep_repy_v2/RUNNABLE
Done building!
~/deep_repy_v2/scripts$ cd ../RUNNABLE/
~/deep_repy_v2/RUNNABLE$
```

`RUNNABLE` now contains a sandbox runtime directory including the HTTPS extensions.

Next, create a file named `get_seattle_webpage.r2py` containing this simple example program:

``` python
log(httpsget("seattle.poly.edu", "GET", "/", None, True), "\n")
```

Run this script like so,

``` bash
~/deep_repy_v2/RUNNABLE$ python repy.py restrictions.default get_seattle_webpage.r2py
```

Your output should be similar to this:

```
(Whatever the output actually looks like; I can't test ATM)
```

Congratulations, you've just written your first program to use the HTTPS-enabled sandbox! This concludes the 5-minute walkthrough.

**Comment by deepjaisia** [comment]
I have made 2 commits to the "Readme" file (the latest one being the final) to update the documentation with a 5-Minute Tutorial that will give the users a lot of help when they are just getting started with the function call and don't want to get much into the hassle of doing of a lot of stuff. The commit that I have made for the same is : d67dbbe.

**Comment by aaaaalbert** [comment]
OK, looks pretty good. Minor notes:
- The **commit message** for d67dbbe should contain parts of your above comment. Our discussion here only lives on GitHub (but not technically inside the repo source tree). Commit messages are stored inside the Git repo.
- I suggest to move the 5-min intro either to the top of the README, or create a separate file for it. Starting the README with a very special test case that requires lots of additional setup deters the reader.
- Since we have five minutes to introduce `httpsget`, let's also work the example and explain what the various arguments into the call are (server URL, HTTP verb, server path, cert file name, and "trust"), and what these mean.

**Comment by deepjaisia** [comment]
19335ae - This is the latest commit to this repository. I have made a new file apart from the "Readme.md" named as "5_min_walkthrough.md" which can be found under SandboxHTTPSExtension repo. I have added a small intro on how to use the call paired with a little description about the arguments that are used in the call.
